"""
generate_manifest.py
Run this once from the same folder as index.html (where your papers/ folder lives).
It scans papers/ and writes papers_manifest.js, which index.html uses to
gray out year buttons for papers that haven't been downloaded yet.

Usage:
    python generate_manifest.py
"""

import os
import json

PAPERS_DIR = './papers'
OUTPUT_FILE = './papers_manifest.js'

def scan_papers(papers_dir):
    available = []
    for root, dirs, files in os.walk(papers_dir):
        dirs.sort()
        for f in sorted(files):
            if f.lower().endswith('.pdf'):
                # Build path relative to index.html: ./papers/ClassX/Subject/file.pdf
                rel = os.path.relpath(os.path.join(root, f), start='.').replace('\\', '/')
                if not rel.startswith('./'):
                    rel = './' + rel
                available.append(rel)
    return available

def main():
    if not os.path.isdir(PAPERS_DIR):
        print(f"ERROR: '{PAPERS_DIR}' folder not found.")
        print("Run this script from the same folder as index.html.")
        return

    available = scan_papers(PAPERS_DIR)

    js_set = json.dumps(available, indent=2, ensure_ascii=False)
    content = f"""// Auto-generated by generate_manifest.py — do not edit manually.
// Re-run generate_manifest.py whenever you add new papers.
const AVAILABLE_PAPERS = new Set(
{js_set}
);
"""
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Done. {len(available)} papers indexed -> {OUTPUT_FILE}")

if __name__ == '__main__':
    main()
